# SPDX-License-Identifier: Apache-2.0

name: Functional tests
description: Run functional tests for MLKEM-C_AArch64

inputs:
  cflags:
    description: CFLAGS to pass to compilation
    default: ''
  cross-prefix:
    description: Binary prefix for cross compilation
    default: ''
runs:
  using: composite
  steps:
      - name: Run functional tests
        id: func_test
        shell: nix develop .#ci -c bash -e {0}
        run: |
          tests func --cross-prefix=${{ inputs.cross-prefix }} --cflags ${{ inputs.cflags }} -v
      - name: Run KAT tests
        if: |
          success()
          || steps.func_test.conclusion == 'failure'
        id: kat_test
        shell: nix develop .#ci -c bash -e {0}
        run: |
          tests kat --cross-prefix=${{ inputs.cross-prefix }} --cflags ${{ inputs.cflags }} -v
      - name: Run Nistkat tests
        id: nistkat_test
        if: |
          success()
          || steps.func_test.conclusion == 'failure'
          || steps.kat_test.conclusion == 'failure'
        shell: nix develop .#ci -c bash -e {0}
        run: |
          tests nistkat --cross-prefix=${{ inputs.cross-prefix }} --cflags ${{ inputs.cflags }} -v
