# SPDX-License-Identifier: Apache-2.0

name: Multiple Functional tests
description: Run functional tests for MLKEM-C_AArch64

inputs:
  nix-shell:
    description: Run in the specified Nix environment if exists
    default: "ci"
  custom_shell:
    description: The shell to use. Only relevant if no nix-shell specified
    default: "bash"
  nix-cache:
    description: Determine whether to enable nix cache
    default: 'true'
  nix-verbose:
    description: Determine wether to suppress nix log or not
    default: 'false'
  cflags:
    description: CFLAGS to pass to compilation
    default: ""
  compile_mode:
    description: all | native | cross
    default: "native"
  opt:
    description: all | opt | no_opt
    default: "all"
  func:
    description: Determine whether to run functional test or not
    default: "true"
  kat:
    description: Determine whether to run kat test or not
    default: "true"
  nistkat:
    description: Determine whether to run nistkat test or not
    default: "true"
runs:
  using: composite
  steps:
      - name: Native Opt Tests
        if: ${{ inputs.compile_mode == 'all' || inputs.compile_mode == 'native' }}
        uses: ./.github/actions/functest
        with:
          nix-shell: ${{ inputs.nix-shell }}
          nix-cache: ${{ inputs.nix-cache }}
          nix-verbose: ${{ inputs.nix-verbose }}
          custom_shell: ${{ inputs.custom_shell }}
          cflags: ${{ inputs.cflags }}
          mode: native
          opt: ${{ inputs.opt }}
          func: ${{ inputs.func }}
          kat: ${{ inputs.kat }}
          nistkat: ${{ inputs.nistkat }}
      - name: Cross Opt Tests
        if: ${{ (inputs.compile_mode == 'all' || inputs.compile_mode == 'cross') && (success() || failure()) }}
        uses: ./.github/actions/functest
        with:
          nix-shell: ${{ inputs.nix-shell }}
          custom_shell: ${{ inputs.custom_shell }}
          cflags: ${{ inputs.cflags }}
          mode: cross
          opt: ${{ inputs.opt }}
          func: ${{ inputs.func }}
          kat: ${{ inputs.kat }}
          nistkat: ${{ inputs.nistkat }}
