name: cbmc-core-reusable
on:
  workflow_call:
    inputs:
      runner:
        type: string
        description: Name of the runner to use
      cross-prefix:
        type: string
        description: Cross-compilation binary prefix, if any
        default: ' '
jobs:
  cbmc:
    name: CBMC ${{ inputs.runner }}
    runs-on: ${{ inputs.runner }}
    defaults:
      run:
        shell: nix develop .#ci-cbmc -c bash -e {0}
    steps:
      - uses: actions/checkout@v4
      - name: Setup nix
        uses: ./.github/actions/setup-nix
        with:
          devShell: ci-cbmc
          script: |
            cat >> $GITHUB_STEP_SUMMARY << EOF
              ## Setup
              Architecture: $(uname -m)
              - $(nix --version)
              - $(cbmc --version)
              - litani Version $(litani --version)
              - Cadical Version $(cadical --version)
              - $(${{ inputs.cross_prefix }}gcc --version | grep -m1 "")
              - $(bash --version | grep -m1 "")
            EOF
      - name: Run CBMC proofs
        run: |
          cd cbmc/proofs;
          KYBER_K=2 ./run-cbmc-proofs.py --summarize;
          KYBER_K=3 ./run-cbmc-proofs.py --summarize;
          KYBER_K=4 ./run-cbmc-proofs.py --summarize;
