# SPDX-License-Identifier: Apache-2.0

name: CI
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]
jobs:
  build_kat:
    strategy:
      fail-fast: false
      matrix:
        external:
         - ${{ github.repository_owner != 'pq-code-package' }}
        target:
         - runner: macos-latest
           name: 'MacOS'
           arch: 'arm64'
           cross-prefix: ' '
           cflags: '-DFORCE_AARCH64'
         - runner: pqcp-arm64
           name: 'ubuntu-latest (aarch64)'
           arch: 'aarch64'
           cross-prefix: ' '
           cflags: '-DFORCE_AARCH64'
         - runner: ubuntu-latest
           name: 'ubuntu-latest (x86_64)'
           arch: 'x86_64'
           cross-prefix: 'aarch64-unknown-linux-gnu-'
           cflags: '-DFORCE_AARCH64'
        exclude:
         - external: true
           target:
             - runner: 'pqcp-arm64'
               name: 'ubuntu-latest (aarch64)'
    name: Functional tests (${{ matrix.target.name }})
    uses: ./.github/workflows/functest_core_reusable.yml
    with:
      runner: ${{ matrix.target.runner }}
      cflags: ${{ matrix.target.cflags }}
      cross-prefix: ${{ matrix.target.cross-prefix }}
  lint:
    strategy:
      matrix:
        system: [ubuntu-latest]
    uses: ./.github/workflows/lint_core_reusable.yml
    with:
      runner: ${{ matrix.system }}
      cross-prefix: "aarch64-unknown-linux-gnu-"
  cbmc:
    strategy:
      matrix:
        system: [macos-latest]
    uses: ./.github/workflows/cbmc_core_reusable.yml
    with:
      runner: ${{ matrix.system }}
      cross-prefix: "aarch64-unknown-linux-gnu-"
