name: functest-core-reusable
on:
  workflow_call:
    inputs:
      runner:
        type: string
        description: Name of the runner to use
      cflags:
        type: string
        description: CFLAGS to pass to compilation
        default: ''
      cross-prefix:
        type: string
        description: Cross-compilation binary prefix, if any
        default: ' '
jobs:
  functest:
    name: Bench ${{ inputs.runner }}
    runs-on: ${{ inputs.runner }}
    defaults:
      run:
        shell: nix develop .#ci -c bash -e {0}
    steps:
      - uses: actions/checkout@v4
      - name: Setup nix
        uses: ./.github/actions/setup-nix
        with:
          devShell: ci
          script: |
            ARCH=$(uname -m)
            cat >> $GITHUB_STEP_SUMMARY <<-EOF
              ## Setup
              Architecture: $ARCH
              - $(uname -a)
              - $(nix --version)
              - $(astyle --version)
              - $(${{ inputs.cross-prefix }}gcc --version | grep -m1 "")
              - $(bash --version | grep -m1 "")
            EOF
      - name: Run functional tests
        uses: ./.github/actions/functest
        with:
          cflags: ${{ inputs.cflags }}
          cross-prefix: ${{ inputs.cross-prefix }}
