name: lint-core-reusable
on:
  workflow_call:
    inputs:
      runner:
        type: string
        description: Name of the runner to use
      cross-prefix:
        type: string
        description: Cross-compilation binary prefix, if any
        default: ' '
jobs:
  lint:
    name: Lint ${{ inputs.runner }}
    runs-on: ${{ inputs.runner }}
    defaults:
      run:
        shell: nix develop .#ci-linter -c bash -e {0}
    steps:
      - uses: actions/checkout@v4
      - name: Setup nix
        uses: ./.github/actions/setup-nix
        with:
          devShell: ci-linter
          script: |
            cat >> $GITHUB_STEP_SUMMARY << EOF
              ## Setup
              Architecture: $(uname -m)
              - $(uname -a)
              - $(nix --version)
              - $(astyle --version)
              - $(${{ matrix.target.cross-prefix }}gcc --version | grep -m1 "")
              - $(bash --version | grep -m1 "")
            EOF
      - name: Lint
        run: |
          echo "## Lint & Checks" >> $GITHUB_STEP_SUMMARY
          lint
