name: Bench
on:
  push:
    branches: ["*"]
jobs:
  bench:
    strategy:
      fail-fast: true
      matrix:
        system: [ macos-latest, linux-latest ]
    runs-on: ${{ matrix.system }}
    steps:
      - name: mac
        if: false
        run: |
          echo "This is mac on ${{ matrix.system }}"

      - name: linux
        if: false
        run: |
          echo "This is linux on ${{ matrix.system }}"
