name: Bench
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [ "labeled" ]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: test
        run: |
          echo "${{github.event}}"
