name: Bench
on:
  push:
    branches: ["*"]
  pull_request:
    types: [ labeled ]
jobs:
  test:
    runs-on: macos-latest
    if: ${{ github.event.label.name == 'benchmark' }}
    steps:
      - name: test
        run: |
          echo "test"
